---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: Kaas-dump
  name: Kaas-dump
  namespace: Kaas-dump

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: Kaas-dump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: Kaas-dump
    namespace: Kaas-dump
