---
apiVersion: v1
kind: Pod
metadata:
  name: Kaas-dump
  labels:
    app: Kaas-dump
spec:
  containers:
    - name: Kaas-dump
      image: woozymasta/Kaas-dump:latest
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 60; done;"]
      env:
        - name: KUBE_CONFIG
          value: /config
      volumeMounts:
        - name: kubeconfig
          mountPath: /config
          subPath: config
          readOnly: true
      resources: {}
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig
        items:
          - key: config
            path: config
