---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: Kaas-dump
  name: Kaas-dump
  namespace: Kaas-dump
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
